In [1]:
import numpy as np

In [4]:
a = [1,1,1,2]
b = [1,1,1,2]

np.array(a)==np.array(b)

array([ True,  True,  True,  True])

In [7]:
np.array([1,2,3,4]) * np.array([-1,-1,-1,-1])

array([-1, -2, -3, -4])

In [3]:
vec = 0.1*np.ones(5)
mat = np.array(range(45)).reshape(5,9)

mat, vec

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44]]),
 array([0.1, 0.1, 0.1, 0.1, 0.1]))

In [7]:
mat[:, -2:]

array([[ 7,  8],
       [16, 17],
       [25, 26],
       [34, 35],
       [43, 44]])

In [22]:
mat - vec[:, np.newaxis]

array([[-0.1,  0.9,  1.9,  2.9,  3.9,  4.9,  5.9,  6.9,  7.9],
       [ 8.9,  9.9, 10.9, 11.9, 12.9, 13.9, 14.9, 15.9, 16.9],
       [17.9, 18.9, 19.9, 20.9, 21.9, 22.9, 23.9, 24.9, 25.9],
       [26.9, 27.9, 28.9, 29.9, 30.9, 31.9, 32.9, 33.9, 34.9],
       [35.9, 36.9, 37.9, 38.9, 39.9, 40.9, 41.9, 42.9, 43.9]])

--------------

In [26]:
probabilities = np.array([[0.3, 0.6, 0.1],
                         [0.7, 0.2, 0.5],
                         [0.4, 0.9, 1]])

In [54]:
np.random.binomial(1, probabilities, size=None)

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1]])

-----------

In [4]:
from util import *

In [6]:
train_imgs,train_lbls,test_imgs,test_lbls = read_mnist(dim=[28,28], n_train=60000, n_test=10000)

In [10]:
train_lbls[2]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)